FROM ghcr.io/neomediatech/ubuntu-base:24.04

ENV SERVICE=exim
      
LABEL org.opencontainers.image.source=https://github.com/Neomediatech/${SERVICE} \
      org.opencontainers.package.name=exim4-daemon-heavy

RUN useradd  -u 5000 -U -s /bin/false -m -d /var/spool/virtual vmail && \
    groupadd -g 5001 Debian-exim && \
    useradd  -g 5001 -u 5001 -s /usr/sbin/nologin -m -d /var/spool/exim4 Debian-exim

# install also 'diceware', to allow generating random words (to anonymi[s|z]e self signed certificate)
RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends mariadb-client exim4-daemon-heavy \
            libswitch-perl redis-tools openssl curl ca-certificates \
            libdbd-sqlite3-perl libdbi-perl diceware && \
    rm -rf /var/lib/apt/lists* && \
    mkdir -p /srv/scripts 

ADD https://raw.githubusercontent.com/Neomediatech/assets/main/scripts/logrotate.sh /srv/scripts/logrotate.sh
COPY bin/* /
RUN chmod +x /entrypoint.sh /gencert.sh /init.sh /srv/scripts/logrotate.sh
RUN /init.sh

EXPOSE 25 465 587

# ToDO: more useful check, like a whole transaction
# HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=20 CMD nc -w 7 -zv 0.0.0.0 25
      
ENTRYPOINT ["/entrypoint.sh"]
#CMD ["/tini","--","/usr/sbin/exim4","-bd","-q1m"]
CMD ["/tini","--","/usr/sbin/exim4","-bd"]
