ARG VERSION \
    SERVICE

FROM ghcr.io/neomediatech/exim:4.96 AS builder

RUN cp /etc/init.d/exim4 ~/exim4.init && \
    cp /etc/default/exim4 ~/exim4.default && \
    dpkg -P exim4-base exim4-daemon-heavy exim4-config && \
    sed -i 's/^# deb-src /deb-src /g' /etc/apt/sources.list && \
    apt-get update 

RUN apt-get install -y --no-install-recommends --no-install-suggests \
       dpkg-dev checkinstall pkg-config \
       pbuilder devscripts grep-dctrl debhelper

RUN mkdir /exim-src && cd /exim-src && \
    apt-get -y source exim4-daemon-heavy && \
    apt-get -y build-dep exim4

RUN cd $(find /exim-src/ -maxdepth 1 -mindepth 1 -type d) && \
    fakeroot debian/rules unpack-configs && \
    apt-get install -y --no-install-recommends --no-install-suggests \
       libopendmarc-dev libspf2-dev libopendmarc2 libspf2-2 && \
    sed -i 's/^# SUPPORT_DMARC=yes/SUPPORT_DMARC=yes/ ; s/^# SUPPORT_SPF=yes/SUPPORT_SPF=yes/' EDITME.exim4-heavy && \
    sed -i 's/^# LDFLAGS += \-lspf2/LDFLAGS += -lspf2/ ; s/^# LDFLAGS += \-lopendmarc/LDFLAGS += -lopendmarc/' EDITME.exim4-heavy && \
    cp -a exim_monitor/EDITME EDITME.eximon && \
    fakeroot debian/rules pack-configs && \
    debuild -us -uc

FROM ghcr.io/neomediatech/exim:4.96

COPY --from=builder "/exim-src/exim4-daemon-heavy_*.deb" "/"

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
       libopendmarc2 libspf2-2 && \
    dpkg -i /exim4-daemon-heavy_*.deb && \
    rm -rf /exim4-daemon-heavy_*.deb /var/lib/apt/lists*



