name: Check Docker images updates on cron

on:
  #schedule:
    # Esegui ogni giorno alle 04:00 UTC per controllare gli aggiornamenti.
    #- cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build-image:
    uses: Neomediatech/gh-workflows/.github/workflows/build-docker-image.yml@main
    with:
      base-image: ghcr.io/neomediatech/ubuntu-base
      package-name: neomediatech/exim
      derived-image-prefix: ghcr.io/neomediatech/exim
      force-build: "false"
      update-image: "true"
      package-to-check: "exim4-daemon-heavy"
    secrets:
      NOTIFY_CMD: ${{ secrets.NOTIFY_CMD }}
      NOTIFY_UP: ${{ secrets.NOTIFY_UP }}
      NOTIFY_ENDPOINT: ${{ secrets.NOTIFY_ENDPOINT }}
      NOTIFY_OPTIONS: ${{ secrets.NOTIFY_OPTIONS }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

